/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RobertNoyes from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface SearchPlantsByStatusRequest {
    /** The status of plants to search for. */
    status?: RobertNoyes.SearchPlantsByStatusRequestStatus;
}
