/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class PlantStoreTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, PlantStoreTimeoutError.prototype);
    }
}
