/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as RobertNoyes from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace User {
    export interface Options {
        environment?: core.Supplier<environments.RobertNoyesEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * Operations about user
 */
export class User {
    protected readonly _options: User.Options;

    constructor(_options: User.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {RobertNoyes.LoginUserRequest} request
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.loginUser()
     */
    public loginUser(
        request: RobertNoyes.LoginUserRequest = {},
        requestOptions?: User.RequestOptions,
    ): core.HttpResponsePromise<RobertNoyes.UserAuthResponse> {
        return core.HttpResponsePromise.fromPromise(this.__loginUser(request, requestOptions));
    }

    private async __loginUser(
        request: RobertNoyes.LoginUserRequest = {},
        requestOptions?: User.RequestOptions,
    ): Promise<core.WithRawResponse<RobertNoyes.UserAuthResponse>> {
        const { username, password } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (username != null) {
            _queryParams["username"] = username;
        }

        if (password != null) {
            _queryParams["password"] = password;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RobertNoyesEnvironment.Default,
                "user/auth/login",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as RobertNoyes.UserAuthResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.RobertNoyesError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RobertNoyesError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.RobertNoyesTimeoutError("Timeout exceeded when calling GET /user/auth/login.");
            case "unknown":
                throw new errors.RobertNoyesError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.logoutUser()
     */
    public logoutUser(requestOptions?: User.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__logoutUser(requestOptions));
    }

    private async __logoutUser(requestOptions?: User.RequestOptions): Promise<core.WithRawResponse<void>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RobertNoyesEnvironment.Default,
                "user/auth/logout",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.RobertNoyesError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RobertNoyesError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.RobertNoyesTimeoutError("Timeout exceeded when calling GET /user/auth/logout.");
            case "unknown":
                throw new errors.RobertNoyesError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve user details using their username.
     *
     * @param {RobertNoyes.GetUserByNameRequest} request
     * @param {User.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.getUserByName({
     *         username: "username"
     *     })
     */
    public getUserByName(
        request: RobertNoyes.GetUserByNameRequest,
        requestOptions?: User.RequestOptions,
    ): core.HttpResponsePromise<RobertNoyes.User> {
        return core.HttpResponsePromise.fromPromise(this.__getUserByName(request, requestOptions));
    }

    private async __getUserByName(
        request: RobertNoyes.GetUserByNameRequest,
        requestOptions?: User.RequestOptions,
    ): Promise<core.WithRawResponse<RobertNoyes.User>> {
        const { username } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RobertNoyesEnvironment.Default,
                `user/${encodeURIComponent(username)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as RobertNoyes.User, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.RobertNoyesError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RobertNoyesError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.RobertNoyesTimeoutError("Timeout exceeded when calling GET /user/{username}.");
            case "unknown":
                throw new errors.RobertNoyesError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
