/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface ListByTagsPlantsRequest {
    /** Tags to filter plants (comma-separated). */
    tags?: string | string[];
}
