/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PlantStore from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListByStatusPlantsRequest {
    /** The status of plants to search for. */
    status?: PlantStore.ListByStatusPlantsRequestStatus;
}
