/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface LoginAuthRequest {
    /** The username for login */
    username?: string;
    /** The password for login */
    password?: string;
}
