/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PlantStore from "../index.js";

export interface PlantCreatedPayload {
    event?: PlantCreatedPayload.Event;
    timestamp?: string;
    data?: PlantStore.PlantResponse;
}

export namespace PlantCreatedPayload {
    export type Event = "plant.created";
    export const Event = {
        PlantCreated: "plant.created",
    } as const;
}
