/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Plant {
    name?: string;
    category?: string;
    tags?: string[];
    status?: Plant.Status;
}

export namespace Plant {
    export type Status = "available" | "pending" | "sold";
    export const Status = {
        Available: "available",
        Pending: "pending",
        Sold: "sold",
    } as const;
}
