/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RobertNoyesDemoApi from "../index.js";

export interface PostPlantUpdatedPayload {
    event?: PostPlantUpdatedPayload.Event;
    timestamp?: string;
    data?: RobertNoyesDemoApi.PlantResponse;
}

export namespace PostPlantUpdatedPayload {
    export type Event = "plant.updated";
    export const Event = {
        PlantUpdated: "plant.updated",
    } as const;
}
