/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserAuthResponse {
    /** Authentication token */
    token?: string;
    /** Token expiration time in seconds */
    expiresIn?: number;
}
