/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WebhookRegistration {
    /** The URL where webhook events will be sent */
    url: string;
    /** List of events to subscribe to */
    events: WebhookRegistration.Events.Item[];
    /** Secret used to sign webhook payloads */
    secret?: string;
}

export namespace WebhookRegistration {
    export type Events = Events.Item[];

    export namespace Events {
        export type Item = "plant.created" | "plant.updated" | "plant.status_changed" | "plant.deleted";
        export const Item = {
            PlantCreated: "plant.created",
            PlantUpdated: "plant.updated",
            PlantStatusChanged: "plant.status_changed",
            PlantDeleted: "plant.deleted",
        } as const;
    }
}
