/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WebhookResponse {
    /** Unique identifier for the webhook */
    id?: string;
    /** The URL where webhook events are sent */
    url?: string;
    /** List of subscribed events */
    events?: string[];
    /** Current status of the webhook */
    status?: WebhookResponse.Status;
}

export namespace WebhookResponse {
    /**
     * Current status of the webhook
     */
    export type Status = "active" | "inactive";
    export const Status = {
        Active: "active",
        Inactive: "inactive",
    } as const;
}
