/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SearchPlantsByStatusRequestStatus = "available" | "pending" | "sold";
export const SearchPlantsByStatusRequestStatus = {
    Available: "available",
    Pending: "pending",
    Sold: "sold",
} as const;
