/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as RobertNoyesDemoApi from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Plant {
    export interface Options {
        environment?: core.Supplier<environments.RobertNoyesDemoApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * Everything about your Plants
 */
export class Plant {
    protected readonly _options: Plant.Options;

    constructor(_options: Plant.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {RobertNoyesDemoApi.Plant} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RobertNoyesDemoApi.MethodNotAllowedError}
     *
     * @example
     *     await client.plant.addPlant({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: "available"
     *     })
     */
    public addPlant(
        request: RobertNoyesDemoApi.Plant,
        requestOptions?: Plant.RequestOptions,
    ): core.HttpResponsePromise<RobertNoyesDemoApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__addPlant(request, requestOptions));
    }

    private async __addPlant(
        request: RobertNoyesDemoApi.Plant,
        requestOptions?: Plant.RequestOptions,
    ): Promise<core.WithRawResponse<RobertNoyesDemoApi.PlantResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RobertNoyesDemoApiEnvironment.Default,
                "plant",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as RobertNoyesDemoApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 405:
                    throw new RobertNoyesDemoApi.MethodNotAllowedError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.RobertNoyesDemoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RobertNoyesDemoApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.RobertNoyesDemoApiTimeoutError("Timeout exceeded when calling POST /plant.");
            case "unknown":
                throw new errors.RobertNoyesDemoApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {RobertNoyesDemoApi.Plant} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link RobertNoyesDemoApi.BadRequestError}
     * @throws {@link RobertNoyesDemoApi.NotFoundError}
     *
     * @example
     *     await client.plant.updatePlant({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: "sold"
     *     })
     */
    public updatePlant(
        request: RobertNoyesDemoApi.Plant,
        requestOptions?: Plant.RequestOptions,
    ): core.HttpResponsePromise<RobertNoyesDemoApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updatePlant(request, requestOptions));
    }

    private async __updatePlant(
        request: RobertNoyesDemoApi.Plant,
        requestOptions?: Plant.RequestOptions,
    ): Promise<core.WithRawResponse<RobertNoyesDemoApi.PlantResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RobertNoyesDemoApiEnvironment.Default,
                "plant",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as RobertNoyesDemoApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new RobertNoyesDemoApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new RobertNoyesDemoApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.RobertNoyesDemoApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RobertNoyesDemoApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.RobertNoyesDemoApiTimeoutError("Timeout exceeded when calling PUT /plant.");
            case "unknown":
                throw new errors.RobertNoyesDemoApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Filter plants based on their current status.
     *
     * @param {RobertNoyesDemoApi.SearchPlantsByStatusRequest} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.searchPlantsByStatus()
     */
    public searchPlantsByStatus(
        request: RobertNoyesDemoApi.SearchPlantsByStatusRequest = {},
        requestOptions?: Plant.RequestOptions,
    ): core.HttpResponsePromise<RobertNoyesDemoApi.PlantResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__searchPlantsByStatus(request, requestOptions));
    }

    private async __searchPlantsByStatus(
        request: RobertNoyesDemoApi.SearchPlantsByStatusRequest = {},
        requestOptions?: Plant.RequestOptions,
    ): Promise<core.WithRawResponse<RobertNoyesDemoApi.PlantResponse[]>> {
        const { status } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (status != null) {
            _queryParams["status"] = status;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RobertNoyesDemoApiEnvironment.Default,
                "plant/search/status",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as RobertNoyesDemoApi.PlantResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.RobertNoyesDemoApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RobertNoyesDemoApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.RobertNoyesDemoApiTimeoutError(
                    "Timeout exceeded when calling GET /plant/search/status.",
                );
            case "unknown":
                throw new errors.RobertNoyesDemoApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Filter plants based on associated tags.
     *
     * @param {RobertNoyesDemoApi.SearchPlantsByTagsRequest} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.searchPlantsByTags()
     */
    public searchPlantsByTags(
        request: RobertNoyesDemoApi.SearchPlantsByTagsRequest = {},
        requestOptions?: Plant.RequestOptions,
    ): core.HttpResponsePromise<RobertNoyesDemoApi.PlantResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__searchPlantsByTags(request, requestOptions));
    }

    private async __searchPlantsByTags(
        request: RobertNoyesDemoApi.SearchPlantsByTagsRequest = {},
        requestOptions?: Plant.RequestOptions,
    ): Promise<core.WithRawResponse<RobertNoyesDemoApi.PlantResponse[]>> {
        const { tags } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (tags != null) {
            if (Array.isArray(tags)) {
                _queryParams["tags"] = tags.map((item) => item);
            } else {
                _queryParams["tags"] = tags;
            }
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RobertNoyesDemoApiEnvironment.Default,
                "plant/search/tags",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as RobertNoyesDemoApi.PlantResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.RobertNoyesDemoApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RobertNoyesDemoApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.RobertNoyesDemoApiTimeoutError(
                    "Timeout exceeded when calling GET /plant/search/tags.",
                );
            case "unknown":
                throw new errors.RobertNoyesDemoApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a plant's details by its ID.
     *
     * @param {RobertNoyesDemoApi.GetPlantByIdRequest} request
     * @param {Plant.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.getPlantById({
     *         plantId: 1
     *     })
     */
    public getPlantById(
        request: RobertNoyesDemoApi.GetPlantByIdRequest,
        requestOptions?: Plant.RequestOptions,
    ): core.HttpResponsePromise<RobertNoyesDemoApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPlantById(request, requestOptions));
    }

    private async __getPlantById(
        request: RobertNoyesDemoApi.GetPlantByIdRequest,
        requestOptions?: Plant.RequestOptions,
    ): Promise<core.WithRawResponse<RobertNoyesDemoApi.PlantResponse>> {
        const { plantId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.RobertNoyesDemoApiEnvironment.Default,
                `plant/${encodeURIComponent(plantId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as RobertNoyesDemoApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.RobertNoyesDemoApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.RobertNoyesDemoApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.RobertNoyesDemoApiTimeoutError("Timeout exceeded when calling GET /plant/{plantId}.");
            case "unknown":
                throw new errors.RobertNoyesDemoApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
