/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { PlantStoreClient } from "../../src/Client";

describe("Auth", () => {
    test("login", async () => {
        const server = mockServerPool.createServer();
        const client = new PlantStoreClient({ environment: server.baseUrl });

        const rawResponseBody = { token: "abc123token", expiresIn: 3600 };
        server.mockEndpoint().get("/user/auth/login").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.auth.login();
        expect(response).toEqual({
            token: "abc123token",
            expiresIn: 3600,
        });
    });

    test("logout", async () => {
        const server = mockServerPool.createServer();
        const client = new PlantStoreClient({ environment: server.baseUrl });

        server.mockEndpoint().get("/user/auth/logout").respondWith().statusCode(200).build();

        const response = await client.auth.logout();
        expect(response).toEqual(undefined);
    });
});
