/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { RobertNoyesDemoApiClient } from "../../src/Client";
import * as RobertNoyesDemoApi from "../../src/api/index";

describe("Plant", () => {
    test("addPlant (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesDemoApiClient({ environment: server.baseUrl });
        const rawRequestBody = { name: "Fern", category: "Indoor", tags: ["green", "leafy"], status: "available" };
        const rawResponseBody = { id: 101, name: "Fern", status: "available", tags: ["green", "leafy"] };
        server
            .mockEndpoint()
            .post("/plant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.plant.addPlant({
            name: "Fern",
            category: "Indoor",
            tags: ["green", "leafy"],
            status: "available",
        });
        expect(response).toEqual({
            id: 101,
            name: "Fern",
            status: "available",
            tags: ["green", "leafy"],
        });
    });

    test("addPlant (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesDemoApiClient({ environment: server.baseUrl });
        const rawRequestBody = { name: undefined, category: undefined, tags: undefined, status: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/plant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(405)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plant.addPlant({
                name: undefined,
                category: undefined,
                tags: undefined,
                status: undefined,
            });
        }).rejects.toThrow(RobertNoyesDemoApi.MethodNotAllowedError);
    });

    test("updatePlant (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesDemoApiClient({ environment: server.baseUrl });
        const rawRequestBody = { name: "Fern", category: "Indoor", tags: ["green", "leafy"], status: "sold" };
        const rawResponseBody = { id: 101, name: "Fern", status: "sold", tags: ["green", "leafy"] };
        server
            .mockEndpoint()
            .put("/plant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.plant.updatePlant({
            name: "Fern",
            category: "Indoor",
            tags: ["green", "leafy"],
            status: "sold",
        });
        expect(response).toEqual({
            id: 101,
            name: "Fern",
            status: "sold",
            tags: ["green", "leafy"],
        });
    });

    test("updatePlant (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesDemoApiClient({ environment: server.baseUrl });
        const rawRequestBody = { name: undefined, category: undefined, tags: undefined, status: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/plant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plant.updatePlant({
                name: undefined,
                category: undefined,
                tags: undefined,
                status: undefined,
            });
        }).rejects.toThrow(RobertNoyesDemoApi.BadRequestError);
    });

    test("updatePlant (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesDemoApiClient({ environment: server.baseUrl });
        const rawRequestBody = { name: undefined, category: undefined, tags: undefined, status: undefined };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/plant")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.plant.updatePlant({
                name: undefined,
                category: undefined,
                tags: undefined,
                status: undefined,
            });
        }).rejects.toThrow(RobertNoyesDemoApi.NotFoundError);
    });

    test("searchPlantsByStatus", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesDemoApiClient({ environment: server.baseUrl });

        const rawResponseBody = [
            { id: 101, name: "Fern", status: "available", tags: ["green", "leafy"] },
            { id: 102, name: "Palm", status: "available", tags: ["tropical"] },
        ];
        server
            .mockEndpoint()
            .get("/plant/search/status")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.plant.searchPlantsByStatus();
        expect(response).toEqual([
            {
                id: 101,
                name: "Fern",
                status: "available",
                tags: ["green", "leafy"],
            },
            {
                id: 102,
                name: "Palm",
                status: "available",
                tags: ["tropical"],
            },
        ]);
    });

    test("searchPlantsByTags", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesDemoApiClient({ environment: server.baseUrl });

        const rawResponseBody = [
            { id: 101, name: "Fern", status: "available", tags: ["green", "leafy"] },
            { id: 103, name: "Cactus", status: "available", tags: ["spiky", "desert"] },
        ];
        server.mockEndpoint().get("/plant/search/tags").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.plant.searchPlantsByTags();
        expect(response).toEqual([
            {
                id: 101,
                name: "Fern",
                status: "available",
                tags: ["green", "leafy"],
            },
            {
                id: 103,
                name: "Cactus",
                status: "available",
                tags: ["spiky", "desert"],
            },
        ]);
    });

    test("getPlantById", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesDemoApiClient({ environment: server.baseUrl });

        const rawResponseBody = { id: 101, name: "Fern", status: "available", tags: ["green", "leafy"] };
        server.mockEndpoint().get("/plant/1").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.plant.getPlantById({
            plantId: 1,
        });
        expect(response).toEqual({
            id: 101,
            name: "Fern",
            status: "available",
            tags: ["green", "leafy"],
        });
    });
});
