/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { PlantStoreClient } from "../../src/Client";

describe("Users", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new PlantStoreClient({ environment: server.baseUrl });

        const rawResponseBody = { id: 1, username: "john_doe", email: "john@example.com" };
        server.mockEndpoint().get("/user/username").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.get({
            username: "username",
        });
        expect(response).toEqual({
            id: 1,
            username: "john_doe",
            email: "john@example.com",
        });
    });
});
