/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { RobertNoyesClient } from "../../src/Client";

describe("User", () => {
    test("loginUser", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesClient({ environment: server.baseUrl });

        const rawResponseBody = { token: "abc123token", expiresIn: 3600 };
        server.mockEndpoint().get("/user/auth/login").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.user.loginUser();
        expect(response).toEqual({
            token: "abc123token",
            expiresIn: 3600,
        });
    });

    test("logoutUser", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesClient({ environment: server.baseUrl });

        server.mockEndpoint().get("/user/auth/logout").respondWith().statusCode(200).build();

        const response = await client.user.logoutUser();
        expect(response).toEqual(undefined);
    });

    test("getUserByName", async () => {
        const server = mockServerPool.createServer();
        const client = new RobertNoyesClient({ environment: server.baseUrl });

        const rawResponseBody = { id: 1, username: "john_doe", email: "john@example.com" };
        server.mockEndpoint().get("/user/username").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.user.getUserByName({
            username: "username",
        });
        expect(response).toEqual({
            id: 1,
            username: "john_doe",
            email: "john@example.com",
        });
    });
});
