/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as PlantStore from "../../../index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Plants {
    export interface Options {
        environment?: core.Supplier<environments.PlantStoreEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Plants {
    protected readonly _options: Plants.Options;

    constructor(_options: Plants.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {PlantStore.Plant} request
     * @param {Plants.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlantStore.MethodNotAllowedError}
     *
     * @example
     *     await client.plants.create({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: "available"
     *     })
     */
    public create(
        request: PlantStore.Plant,
        requestOptions?: Plants.RequestOptions,
    ): core.HttpResponsePromise<PlantStore.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: PlantStore.Plant,
        requestOptions?: Plants.RequestOptions,
    ): Promise<core.WithRawResponse<PlantStore.PlantResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlantStoreEnvironment.Default,
                "plant",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as PlantStore.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 405:
                    throw new PlantStore.MethodNotAllowedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlantStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PlantStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PlantStoreTimeoutError("Timeout exceeded when calling POST /plant.");
            case "unknown":
                throw new errors.PlantStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {PlantStore.Plant} request
     * @param {Plants.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PlantStore.BadRequestError}
     * @throws {@link PlantStore.NotFoundError}
     *
     * @example
     *     await client.plants.update({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: "sold"
     *     })
     */
    public update(
        request: PlantStore.Plant,
        requestOptions?: Plants.RequestOptions,
    ): core.HttpResponsePromise<PlantStore.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: PlantStore.Plant,
        requestOptions?: Plants.RequestOptions,
    ): Promise<core.WithRawResponse<PlantStore.PlantResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlantStoreEnvironment.Default,
                "plant",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as PlantStore.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PlantStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new PlantStore.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PlantStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PlantStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PlantStoreTimeoutError("Timeout exceeded when calling PUT /plant.");
            case "unknown":
                throw new errors.PlantStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Filter plants based on their current status.
     *
     * @param {PlantStore.ListByStatusPlantsRequest} request
     * @param {Plants.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plants.listByStatus()
     */
    public listByStatus(
        request: PlantStore.ListByStatusPlantsRequest = {},
        requestOptions?: Plants.RequestOptions,
    ): core.HttpResponsePromise<PlantStore.PlantResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__listByStatus(request, requestOptions));
    }

    private async __listByStatus(
        request: PlantStore.ListByStatusPlantsRequest = {},
        requestOptions?: Plants.RequestOptions,
    ): Promise<core.WithRawResponse<PlantStore.PlantResponse[]>> {
        const { status } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (status != null) {
            _queryParams["status"] = status;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlantStoreEnvironment.Default,
                "plant/search/status",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as PlantStore.PlantResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PlantStoreError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PlantStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PlantStoreTimeoutError("Timeout exceeded when calling GET /plant/search/status.");
            case "unknown":
                throw new errors.PlantStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Filter plants based on associated tags.
     *
     * @param {PlantStore.ListByTagsPlantsRequest} request
     * @param {Plants.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plants.listByTags()
     */
    public listByTags(
        request: PlantStore.ListByTagsPlantsRequest = {},
        requestOptions?: Plants.RequestOptions,
    ): core.HttpResponsePromise<PlantStore.PlantResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__listByTags(request, requestOptions));
    }

    private async __listByTags(
        request: PlantStore.ListByTagsPlantsRequest = {},
        requestOptions?: Plants.RequestOptions,
    ): Promise<core.WithRawResponse<PlantStore.PlantResponse[]>> {
        const { tags } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (tags != null) {
            if (Array.isArray(tags)) {
                _queryParams["tags"] = tags.map((item) => item);
            } else {
                _queryParams["tags"] = tags;
            }
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlantStoreEnvironment.Default,
                "plant/search/tags",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as PlantStore.PlantResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PlantStoreError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PlantStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PlantStoreTimeoutError("Timeout exceeded when calling GET /plant/search/tags.");
            case "unknown":
                throw new errors.PlantStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a plant's details by its ID.
     *
     * @param {PlantStore.GetPlantsRequest} request
     * @param {Plants.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plants.get({
     *         plantId: 1
     *     })
     */
    public get(
        request: PlantStore.GetPlantsRequest,
        requestOptions?: Plants.RequestOptions,
    ): core.HttpResponsePromise<PlantStore.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: PlantStore.GetPlantsRequest,
        requestOptions?: Plants.RequestOptions,
    ): Promise<core.WithRawResponse<PlantStore.PlantResponse>> {
        const { plantId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PlantStoreEnvironment.Default,
                `plant/${encodeURIComponent(plantId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as PlantStore.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PlantStoreError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PlantStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PlantStoreTimeoutError("Timeout exceeded when calling GET /plant/{plantId}.");
            case "unknown":
                throw new errors.PlantStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
