/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Plants } from "./api/resources/plants/client/Client.js";
import { Auth } from "./api/resources/auth/client/Client.js";
import { Users } from "./api/resources/users/client/Client.js";

export declare namespace PlantStoreClient {
    export interface Options {
        environment?: core.Supplier<environments.PlantStoreEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class PlantStoreClient {
    protected readonly _options: PlantStoreClient.Options;
    protected _plants: Plants | undefined;
    protected _auth: Auth | undefined;
    protected _users: Users | undefined;

    constructor(_options: PlantStoreClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "plantstore-typescript-sdk",
                    "X-Fern-SDK-Version": "0.0.5",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get plants(): Plants {
        return (this._plants ??= new Plants(this._options));
    }

    public get auth(): Auth {
        return (this._auth ??= new Auth(this._options));
    }

    public get users(): Users {
        return (this._users ??= new Users(this._options));
    }
}
