/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Plant } from "./api/resources/plant/client/Client.js";
import { User } from "./api/resources/user/client/Client.js";

export declare namespace RobertNoyesDemoApiClient {
    export interface Options {
        environment?: core.Supplier<environments.RobertNoyesDemoApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class RobertNoyesDemoApiClient {
    protected readonly _options: RobertNoyesDemoApiClient.Options;
    protected _plant: Plant | undefined;
    protected _user: User | undefined;

    constructor(_options: RobertNoyesDemoApiClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "robert-noyes-typescript-sdk",
                    "X-Fern-SDK-Version": "0.0.3",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get plant(): Plant {
        return (this._plant ??= new Plant(this._options));
    }

    public get user(): User {
        return (this._user ??= new User(this._options));
    }
}
