/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const RobertNoyesEnvironment = {
    Default: "https://api.plantstore.dev/v3",
} as const;

export type RobertNoyesEnvironment = typeof RobertNoyesEnvironment.Default;
