/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PlantStoreEnvironment = {
    Default: "https://api.plantstore.dev/v3",
} as const;

export type PlantStoreEnvironment = typeof PlantStoreEnvironment.Default;
