/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         username: "username"
 *     }
 */
export interface GetUsersRequest {
    /** Username of the user to retrieve */
    username: string;
}
